include:
  - board: corneish_zen_v2_left
  - board: corneish_zen_v2_right
  - board: mnt_pocket_reform
    cmake-args: '"-DBOARD_ROOT=${GITHUB_WORKSPACE}/pocket-reform-zmk-config/config/"'
  - board: seeeduino_xiao_ble
    shield: revxlp
    cmake-args: '"-DBOARD_ROOT=${GITHUB_WORKSPACE}/revxlp-config/config/"'
