manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware/
    - name: petejohanson
      url-base: https://github.com/petejohanson/
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: HEAD
      import: app/west.yml
    - name: revxlp-config
      remote: petejohanson
      revision: HEAD
  self:
    path: config/
